### ISSUE TITLE
when to release the code

### ISSUE THREAD

**Issue by Maguire1999** [ChaoyueSong/MoDA#1]
Hello , it is a great work! Look forward to releasing.

**Comment by ChaoyueSong** [comment]
Hi, thanks for your interest. Sorry that I cannot give an exact date, but I guess it may be in three months.

**Comment by Maguire1999** [comment]
OK, thanks



---Original---
From: "Chaoyue ***@***.***&gt;
Date: Tue, May 30, 2023 16:43 PM
To: ***@***.***&gt;;
Cc: "Yongjia ***@***.******@***.***&gt;;
Subject: Re: [ChaoyueSong/MoDA] when to release the code (Issue #1)




 
Hi, thanks for your interest. Sorry that I cannot give an exact date, but I guess it may be in three months.
