### ISSUE TITLE
Supplement Paper

### ISSUE THREAD

**Issue by AndyWangZH** [ChaoyueSong/MoDA#2]
Hi there!
Thanks for your nice work.
I am wondering when will you release your supplement paper since several details were claimed to be in supplement but somehow I cannot find the supplement in the web.
I am looking forward a detail description about your neural skinning weights network and loss function.
Best regards!
Andy Wang

**Comment by ChaoyueSong** [comment]
Hi,
Thanks for your interest. We have updated the paper with appendices on the project page.
